[package]
name = "components"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_axum.workspace = true
leptos.workspace = true
leptos_icons.workspace = true
icondata.workspace = true
web-sys.workspace = true
http.workspace = true
thiserror.workspace = true

[features]
ssr = ["leptos/ssr"]